### ISSUE TITLE
Algorythm? 

### ISSUE THREAD

**Issue by iam4x** [mahmalsami/limitation-loyers-paris#1]
I wanted to know where does the data comes from to estimate the prices. Thanks.

**Comment by mahmalsami** [comment]
Hi @iam4x , i took the datas from various online verified sources.
You have the whole official document http://www.drihl.ile-de-france.developpement-durable.gouv.fr/IMG/pdf/Arrete_no2015_176_-_0007_cle5d1377.pdf
at your disposition !

**Comment by iam4x** [comment]
Great, thank you.

**Comment by mahmalsami** [comment]
@iam4x , also, if you check a random website, you can easily check for the loaded xml data (for example http://www.observatoire-des-loyers.fr/loyers/medianes ) from you Developper Javascript console.
